### PR TITLE
Enabled CORS.

### PR DESCRIPTION
**Pull request by markokramer**

### CODE REVIEW

**Comment by markokramer** [comment]
Mistake. Wanted to create a pull request on a branch https://github.com/databox/osprey-mock-service.

**Comment by blakeembrey** [comment]
No worries. I just looked at the changes though and it looks like you just wanted to enable CORS? Would it be helpful if an option was added to enable CORS for you?

**Comment by markokramer** [comment]
Thanks, would be very useful. We need CORS, because we are mocking our webapp backend in a separate docker container.

**Comment by blakeembrey** [comment]
@markokramer No worries. I'll make sure it's in the next beta of Osprey and it'll start working. I've needed it enable it before too.

**Comment by blakeembrey** [comment]
@markokramer I just pushed a few intense changes with Osprey (the error handler is kind of cool) and it includes CORS support using the `--cors` option. Can you let me know if it works for you?

**Comment by markokramer** [comment]
@blakeembrey I just did a quick test and it appears to be working. Thanks, great work. The error handler is a usefull improvement too.

**Pull request closed without merging**
